# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# (mostly) auto-generated by cargo-ebuild 0.5.2

EAPI=8

CRATES="
	adler-1.0.2
	aho-corasick-0.7.19
	ansi_colours-1.1.1
	ansi_term-0.12.1
	atty-0.2.14
	autocfg-1.1.0
	bat-0.22.1
	bincode-1.3.3
	bit-set-0.5.3
	bit-vec-0.6.3
	bitflags-1.3.2
	bstr-0.2.17
	bytemuck-1.12.3
	bytesize-1.1.0
	cargo-subcommand-metadata-0.1.0
	cfg-if-1.0.0
	clap-4.0.26
	clap_derive-4.0.21
	clap_lex-0.3.0
	clircle-0.3.0
	console-0.15.2
	content_inspector-0.2.4
	crc32fast-1.3.2
	encode_unicode-0.3.6
	encoding-0.2.33
	encoding-index-japanese-1.20141219.5
	encoding-index-korean-1.20141219.5
	encoding-index-simpchinese-1.20141219.5
	encoding-index-singlebyte-1.20141219.5
	encoding-index-tradchinese-1.20141219.5
	encoding_index_tests-0.1.4
	fancy-regex-0.7.1
	fastrand-1.8.0
	flate2-1.0.24
	fnv-1.0.7
	globset-0.4.9
	grep-cli-0.1.6
	hashbrown-0.12.3
	heck-0.4.0
	hermit-abi-0.1.19
	home-0.5.4
	indexmap-1.9.2
	instant-0.1.12
	itoa-1.0.4
	lazy_static-1.4.0
	libc-0.2.137
	linked-hash-map-0.5.6
	log-0.4.17
	memchr-2.5.0
	miniz_oxide-0.5.4
	once_cell-1.16.0
	os_str_bytes-6.4.1
	path_abs-0.5.1
	pest-2.4.1
	prettyplease-0.1.21
	proc-macro-error-1.0.4
	proc-macro-error-attr-1.0.4
	proc-macro2-1.0.47
	quote-1.0.21
	redox_syscall-0.2.16
	regex-1.7.0
	regex-automata-0.1.10
	regex-syntax-0.6.28
	remove_dir_all-0.5.3
	rgb-0.8.34
	ryu-1.0.11
	same-file-1.0.6
	semver-0.11.0
	semver-1.0.14
	semver-parser-0.10.2
	serde-1.0.147
	serde_derive-1.0.147
	serde_json-1.0.88
	serde_yaml-0.8.26
	shell-words-1.1.0
	std_prelude-0.2.12
	strsim-0.10.0
	syn-1.0.103
	syn-select-0.2.1
	syntect-5.0.0
	tempfile-3.3.0
	termcolor-1.1.3
	terminal_size-0.1.17
	thiserror-1.0.37
	thiserror-impl-1.0.37
	toml-0.5.9
	toolchain_find-0.2.0
	ucd-trie-0.1.5
	unicode-ident-1.0.5
	unicode-width-0.1.10
	version_check-0.9.4
	walkdir-2.3.2
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	yaml-rust-0.4.5
"

inherit cargo

DESCRIPTION="Cargo subcommand to show result of macro expansion"
HOMEPAGE="https://github.com/dtolnay/cargo-expand"
SRC_URI="
	https://github.com/dtolnay/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris)
"

LICENSE="0BSD Apache-2.0 BSD Boost-1.0 CC0-1.0 LGPL-3+ MIT Unicode-DFS-2016 Unlicense ZLIB"
SLOT="0"
KEYWORDS="~amd64"

DOCS=(
	"README.md"
)

src_install() {
	cargo_src_install
	einstalldocs
}
